# Discovery Server Access
port:
  eurekaServer: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${port.eurekaServer}/eureka
  instance:
    initial-status: UP
    lease-renewal-interval-in-seconds: 300

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice_cesta
    username: microservice_cesta
    password: microservice_cesta
  jpa:
    generate-ddl: true
